### ISSUE TITLE
Room vs Instance usage

### ISSUE THREAD

**Issue by msub2** [nurse-the-code/hubs-directory#2]
The description of the repo is as a list of Hubs *instances*, but the first link in the table is to a specific Hubs *room*, and the instructions for adding entries also use room. My understanding is that this list is meant to serve as a directory of Hubs Community Edition deployments, so clarifying this would be helpful.

**Comment by nurse-the-code** [comment]
Thanks for asking for a clarification here. My intention was for this to be a list of rooms that are intentionally shared with the Hubs community. There may very well be merit in creating a separate list of Hubs deployments.

**Comment by msub2** [comment]
Ahhh gotcha, thank you! In that case I'll add the WebXR Discord Monthly Meetup room here soon.

**Comment by nurse-the-code** [comment]
I made a [commit](https://github.com/nurse-the-code/hubs-directory/commit/e3e72e68912da2b93b168ce29d924a24adefe5ad) to clarify this issue. I am closing this issue in favor of [Issue # : Consider adding list of Hubs deployments](https://github.com/nurse-the-code/hubs-directory/issues/3).
